#!/usr/bin/env bash
#display hello world ten times using while and bad luck for 4th and good luck for 8th

n=0
while ((n++ < 10))
do
	if [ $n -eq 4 ]
	then
			echo "bad luck"
	elif [ $n -eq 8 ]
	then
			echo "good luck"
	else
		echo "Best School"
	fi
done
