#!/usr/bin/env bash
#display hello world ten times using while and bad luck for 4th and good luck for 8th

n=0
while ((n++ < 20))
do
	case $n in
		4)
			echo $n
			echo "bad luck from China"
			;;
		8)
			echo $n
			echo "bad luck from Japan"
			;;
		17)
			echo $n
			echo "bad luck from Italy"
			;;
		*)
			echo $n
			;;
	esac
done
