#!/usr/bin/env bash
#display hello world ten times using while and bad luck for 4th and good luck for 8th

counter=1
while [ $counter -lt 21 ]; do
	echo $counter
	case $counter in
	4)
	echo "bad luck from China";;
	9)
	echo "bad luck from Japan";;
	17)
	echo "bad luck from Italy";;
 	esac
	(( counter+=1 ))
done 
