#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minute

hr=0
min=1
while [ $hr -lt 13 ]; do
	echo "Hour: $hr"
	while [ $min -lt 60 ]; do
		echo $min
		(( min+=1 ))
	done
	min=1
	(( hr+=1 ))
done 
